baseURL = 'https://shenchih20.github.io/schnotes/'
languageCode = 'en-us'
title = 'SCH notes'

# Language settings
contentDir = "content/zh"
defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

enableRobotsTXT = true

# You can add your own taxonomies
[taxonomies]
tag = "tags"
category = "categories"

# UI config
[params]
[params.ui]
showLightDarkModeMenu = true


# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser.attribute]
      block = true
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
    style = "tango"
    # Uncomment if you want your chosen highlight style used for code blocks without a specified language
    # guessSyntax = "true"


# Language configuration

[languages]
[languages.zh]
languageName ="繁體中文"
title = "SCH notes"
[languages.zh.params]
description = "The notes of Shen-Chih Hsu"


[module]
# proxy = "direct"
# uncomment line below for temporary local development of module
# replacements = "github.com/google/docsy -> ../../docsy"
[module.hugoVersion]
extended = true
min = "0.110.0"
[[module.imports]]
path = "github.com/google/docsy"
disable = false
